// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: proto/drips.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DripsServiceClient is the client API for DripsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DripsServiceClient interface {
	Routine(ctx context.Context, in *RoutineRequest, opts ...grpc.CallOption) (*RoutineResponse, error)
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type dripsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDripsServiceClient(cc grpc.ClientConnInterface) DripsServiceClient {
	return &dripsServiceClient{cc}
}

func (c *dripsServiceClient) Routine(ctx context.Context, in *RoutineRequest, opts ...grpc.CallOption) (*RoutineResponse, error) {
	out := new(RoutineResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/Routine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DripsServiceServer is the server API for DripsService service.
// All implementations must embed UnimplementedDripsServiceServer
// for forward compatibility
type DripsServiceServer interface {
	Routine(context.Context, *RoutineRequest) (*RoutineResponse, error)
	User(context.Context, *UserRequest) (*UserResponse, error)
	mustEmbedUnimplementedDripsServiceServer()
}

// UnimplementedDripsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDripsServiceServer struct {
}

func (UnimplementedDripsServiceServer) Routine(context.Context, *RoutineRequest) (*RoutineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Routine not implemented")
}
func (UnimplementedDripsServiceServer) User(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}
func (UnimplementedDripsServiceServer) mustEmbedUnimplementedDripsServiceServer() {}

// UnsafeDripsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DripsServiceServer will
// result in compilation errors.
type UnsafeDripsServiceServer interface {
	mustEmbedUnimplementedDripsServiceServer()
}

func RegisterDripsServiceServer(s grpc.ServiceRegistrar, srv DripsServiceServer) {
	s.RegisterService(&DripsService_ServiceDesc, srv)
}

func _DripsService_Routine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).Routine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/Routine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).Routine(ctx, req.(*RoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DripsService_ServiceDesc is the grpc.ServiceDesc for DripsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DripsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drips.DripsService",
	HandlerType: (*DripsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Routine",
			Handler:    _DripsService_Routine_Handler,
		},
		{
			MethodName: "User",
			Handler:    _DripsService_User_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/drips.proto",
}
