// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/drips.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DripsServiceClient is the client API for DripsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DripsServiceClient interface {
	ExerciseClass(ctx context.Context, in *ExerciseClassRequest, opts ...grpc.CallOption) (*ExerciseClassResponse, error)
	ExerciseClasses(ctx context.Context, in *ExerciseClassesRequest, opts ...grpc.CallOption) (*ExerciseClassesResponse, error)
	ExerciseClassCreate(ctx context.Context, in *ExerciseClassCreateRequest, opts ...grpc.CallOption) (*ExerciseClassCreateResponse, error)
	ExerciseClassDelete(ctx context.Context, in *ExerciseClassDeleteRequest, opts ...grpc.CallOption) (*ExerciseClassDeleteResponse, error)
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error)
}

type dripsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDripsServiceClient(cc grpc.ClientConnInterface) DripsServiceClient {
	return &dripsServiceClient{cc}
}

func (c *dripsServiceClient) ExerciseClass(ctx context.Context, in *ExerciseClassRequest, opts ...grpc.CallOption) (*ExerciseClassResponse, error) {
	out := new(ExerciseClassResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/ExerciseClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) ExerciseClasses(ctx context.Context, in *ExerciseClassesRequest, opts ...grpc.CallOption) (*ExerciseClassesResponse, error) {
	out := new(ExerciseClassesResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/ExerciseClasses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) ExerciseClassCreate(ctx context.Context, in *ExerciseClassCreateRequest, opts ...grpc.CallOption) (*ExerciseClassCreateResponse, error) {
	out := new(ExerciseClassCreateResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/ExerciseClassCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) ExerciseClassDelete(ctx context.Context, in *ExerciseClassDeleteRequest, opts ...grpc.CallOption) (*ExerciseClassDeleteResponse, error) {
	out := new(ExerciseClassDeleteResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/ExerciseClassDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/Users", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/UserCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dripsServiceClient) UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error) {
	out := new(UserDeleteResponse)
	err := c.cc.Invoke(ctx, "/drips.DripsService/UserDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DripsServiceServer is the server API for DripsService service.
// All implementations must embed UnimplementedDripsServiceServer
// for forward compatibility
type DripsServiceServer interface {
	ExerciseClass(context.Context, *ExerciseClassRequest) (*ExerciseClassResponse, error)
	ExerciseClasses(context.Context, *ExerciseClassesRequest) (*ExerciseClassesResponse, error)
	ExerciseClassCreate(context.Context, *ExerciseClassCreateRequest) (*ExerciseClassCreateResponse, error)
	ExerciseClassDelete(context.Context, *ExerciseClassDeleteRequest) (*ExerciseClassDeleteResponse, error)
	User(context.Context, *UserRequest) (*UserResponse, error)
	Users(context.Context, *UsersRequest) (*UsersResponse, error)
	UserCreate(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	UserDelete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error)
	mustEmbedUnimplementedDripsServiceServer()
}

// UnimplementedDripsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDripsServiceServer struct {
}

func (UnimplementedDripsServiceServer) ExerciseClass(context.Context, *ExerciseClassRequest) (*ExerciseClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExerciseClass not implemented")
}
func (UnimplementedDripsServiceServer) ExerciseClasses(context.Context, *ExerciseClassesRequest) (*ExerciseClassesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExerciseClasses not implemented")
}
func (UnimplementedDripsServiceServer) ExerciseClassCreate(context.Context, *ExerciseClassCreateRequest) (*ExerciseClassCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExerciseClassCreate not implemented")
}
func (UnimplementedDripsServiceServer) ExerciseClassDelete(context.Context, *ExerciseClassDeleteRequest) (*ExerciseClassDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExerciseClassDelete not implemented")
}
func (UnimplementedDripsServiceServer) User(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}
func (UnimplementedDripsServiceServer) Users(context.Context, *UsersRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Users not implemented")
}
func (UnimplementedDripsServiceServer) UserCreate(context.Context, *UserCreateRequest) (*UserCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCreate not implemented")
}
func (UnimplementedDripsServiceServer) UserDelete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedDripsServiceServer) mustEmbedUnimplementedDripsServiceServer() {}

// UnsafeDripsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DripsServiceServer will
// result in compilation errors.
type UnsafeDripsServiceServer interface {
	mustEmbedUnimplementedDripsServiceServer()
}

func RegisterDripsServiceServer(s grpc.ServiceRegistrar, srv DripsServiceServer) {
	s.RegisterService(&DripsService_ServiceDesc, srv)
}

func _DripsService_ExerciseClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExerciseClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).ExerciseClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/ExerciseClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).ExerciseClass(ctx, req.(*ExerciseClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_ExerciseClasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExerciseClassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).ExerciseClasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/ExerciseClasses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).ExerciseClasses(ctx, req.(*ExerciseClassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_ExerciseClassCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExerciseClassCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).ExerciseClassCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/ExerciseClassCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).ExerciseClassCreate(ctx, req.(*ExerciseClassCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_ExerciseClassDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExerciseClassDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).ExerciseClassDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/ExerciseClassDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).ExerciseClassDelete(ctx, req.(*ExerciseClassDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/Users",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).Users(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/UserCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).UserCreate(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DripsService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DripsServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drips.DripsService/UserDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DripsServiceServer).UserDelete(ctx, req.(*UserDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DripsService_ServiceDesc is the grpc.ServiceDesc for DripsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DripsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drips.DripsService",
	HandlerType: (*DripsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExerciseClass",
			Handler:    _DripsService_ExerciseClass_Handler,
		},
		{
			MethodName: "ExerciseClasses",
			Handler:    _DripsService_ExerciseClasses_Handler,
		},
		{
			MethodName: "ExerciseClassCreate",
			Handler:    _DripsService_ExerciseClassCreate_Handler,
		},
		{
			MethodName: "ExerciseClassDelete",
			Handler:    _DripsService_ExerciseClassDelete_Handler,
		},
		{
			MethodName: "User",
			Handler:    _DripsService_User_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _DripsService_Users_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _DripsService_UserCreate_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _DripsService_UserDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/drips.proto",
}
